[package]
name = "charcoal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fern = "0.6.2"
kafka = "0.9.0"
log = "0.4.17"
openssl = "0.10.52"
serde = "1.0.162"
serde_derive = "1.0.163"
serde_json = "1.0.96"
snafu = "0.7.4"
tokio = { version = "1.28.1", features = ['full'] }

[dependencies.hearth-interconnect]
git = "https://github.com/Hearth-Industries/hearth-interconnect.git"
